
spring:
  datasource:
    url: jdbc:mysql://sms-db:3306/sms_db?allowMultiQueries=true
    username: sms_user
    password: sms_password
    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:mysql://localhost:3306/sms_service?allowMultiQueries=true
#    username: root
#    password: Bolshov92
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master-sms.xml

  kafka:
    consumer:
      group-id: sms-service-group
    topic:
      name: sms-topic

twilio:
  account-sid:  ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}