eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  main:
    banner-mode: off
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/sms_service?allowMultiQueries=true
    username: root
    password: Bolshov92
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  liquibase:
    change-log: classpath:/db/changelog/changelog-master-sms.xml

  kafka:
    consumer:
      group-id: sms-service-group
    topic:
      name: sms-topic


logging:
  level:
    root: INFO
    com.example.construction_company_management: DEBUG


twilio:
  account-sid:  ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}