version: '3.8'
services:
  contact-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: contacts_db
      MYSQL_USER: contact_user
      MYSQL_PASSWORD: contact_password
    ports:
      - "3307:3306"
    volumes:
      - contact-db-data:/var/lib/mysql

  event-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: events_db
      MYSQL_USER: event_user
      MYSQL_PASSWORD: event_password
    ports:
      - "3308:3306"
    volumes:
      - event-db-data:/var/lib/mysql

  file-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: files_db
      MYSQL_USER: file_user
      MYSQL_PASSWORD: file_password
    ports:
      - "3309:3306"
    volumes:
      - file-db-data:/var/lib/mysql

  notification-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: notifications_db
      MYSQL_USER: notification_user
      MYSQL_PASSWORD: notification_password
    ports:
      - "3310:3306"
    volumes:
      - notification-db-data:/var/lib/mysql

  sms-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: sms_db
      MYSQL_USER: sms_user
      MYSQL_PASSWORD: sms_password
    ports:
      - "3311:3306"
    volumes:
      - sms-db-data:/var/lib/mysql

  user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: users_db
      MYSQL_USER: user_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3312:3306"
    volumes:
      - user-db-data:/var/lib/mysql

volumes:
  contact-db-data:
  event-db-data:
  file-db-data:
  notification-db-data:
  sms-db-data:
  user-db-data: