spring:
  cloud:
    gateway:
      routes:
        - id: sms-service
          uri: lb://SMS-SERVICE
          predicates:
            - Path=/sms/**
        - id: contact-service
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path=/contacts/**