eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  datasource:
    url: jdbc:mysql://localhost:3306/file_service?allowMultiQueries=true
    username: root
    password: Bolshov92
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always