<<<<<<< HEAD
server:
  port: 8083
=======
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_service?allowMultiQueries=true
    username: root
    password: Bolshov92
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
>>>>>>> 86b55d78e87e0fb261af64ab093892b1a218c909

spring:
  datasource:
    url: jdbc:mysql://file-db:3306/files_db?allowMultiQueries=true
    username: file_user
    password: file_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master-file-service.xml
<<<<<<< HEAD
  kafka:
    consumer:
      group-id: file-service-group
    topic:
      name: file-topic
=======
>>>>>>> 86b55d78e87e0fb261af64ab093892b1a218c909
