
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/file_service?allowMultiQueries=true
#    username: root
#    password: Bolshov92
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always

spring:
  datasource:
    url: jdbc:mysql://file-db:3306/files_db?allowMultiQueries=true
    username: file_user
    password: file_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master-file-service.xml

  kafka:
    consumer:
      group-id: file-service-group
    topic:
      name: file-topic
