spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?allowMultiQueries=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/contact_service?allowMultiQueries=true
  #    username: root
  #    password: Bolshov92
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master-contact-service.xml

  kafka:
    consumer:
      group-id: contact-group
    topic:
      name: contact-topic

