server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://contact-db:3306/contacts_db?allowMultiQueries=true
    username: contact_user
    password: contact_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master-contact-service.xml

  kafka:
    consumer:
      group-id: contact-service-group
    topic:
      name: contact-topic