name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker build -t bolshov92/contact-service ./contact-service
          docker build -t bolshov92/event-service ./event-service
          docker build -t bolshov92/file-service ./file-service
          docker build -t bolshov92/notification-service ./notification-service
          docker build -t bolshov92/sms-service ./sms-service
          docker build -t bolshov92/user-service ./user-service

      - name: Push Docker images
        run: |
          docker push bolshov92/contact-service
          docker push bolshov92/event-service
          docker push bolshov92/file-service
          docker push bolshov92/notification-service
          docker push bolshov92/sms-service
          docker push bolshov92/user-service

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
